FROM java19:latest

# FROM buildpack-deps:xenial-scm

# See http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
# for Java 9 installation instructions.
# RUN apt-get -y update && \
#     apt-get install -y software-properties-common && \
#     echo oracle-java9-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
#     add-apt-repository ppa:webupd8team/java && \
#     apt-get update && \
#     apt-get install -y oracle-java9-installer && \
#     apt-get install -y oracle-java9-set-default && \
#     apt-get install -y ca-certificates-java && \
#     apt-get install -y telnet

# See https://www.postgresql.org/download/linux/ubuntu/
RUN apt-get -y update && \
    echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get -y update && \
    apt-get install -y postgresql-client && \
    apt-get install -y telnet

WORKDIR /usr/local/bin
RUN wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && \
    chmod 755 lein && \
    ./lein
RUN printf '#!/bin/sh\nlein trampoline run -m clojure.main\n' > repl && \
    chmod 755 repl

RUN echo 'PS1="clj-dev:\u@\h:\w# "' >> /root/.bashrc

RUN mkdir /myapp
WORKDIR /myapp

